version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    environment:
      - PORT=3000
    # env_file:             #to pass whole environment file
    #   - ./.env
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ashish
      - MONGO_INITDB_ROOT_PASSWORD=pass123
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis


volumes:
  mongo-db: